syntax = "proto3";

package downlink;

message Message {
  oneof msg {
    VehicleState state = 1;
    VehicleHealth health = 2;
    MissionStatus status = 3;
  }
}

message VehicleState {
  float x = 1;
  float y = 2;
  float z = 3;
  float x_v = 4;
  float y_v = 5;
  float z_v = 6;
  float yaw_degrees = 7;
  float range_front = 10;
  float range_back = 11;
  float range_right = 12;
  float range_left = 13;
  float range_up = 14;
}

message VehicleHealth {
  enum BatteryLevel {
    BATTERY_LEVEL_UNSPECIFIED = 0;
    Low = 1;
    High = 2;
  }
  BatteryLevel   battery_level = 1;
}

message MissionStatus {
  message Running {
    message Progress {
      string current_command = 1;
      uint32 command_num = 2;
      uint32 total_commands = 3;
    }
    Progress p = 1;
  }
  message Aborted {
    enum Reason {
      HardStop = 0;
      LowBattery = 1;
    }
    Reason reason = 1;
  }
  message Idle {}
  message Landing {}
  oneof status {
    Idle idle = 1;
    Running running = 2;
    Aborted aborted = 3;
    Landing landing = 4;
  }
}
