name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
        SQLX_OFFLINE: "true" # needed as database url is present, to make compiling without postgres possible
    steps:
    - uses: actions/checkout@v5
    - uses: actions/cache@v4     
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-${{ runner.os }}-
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv

    - name: Build the devenv shell and run any pre-commit hooks
      run: devenv test
